variables:
  VERCEL_TOKEN: RYuYuyxj2Kexdzey9N8694lT
  VERCEL_ORG_ID: team_TVQXy6uF9400va3TRYpPar4D
  VERCEL_PROJECT_ID: prj_G5JPS5FxYCbtjq31YQ2bQ76jB5l3

stages:
  - build
  - misc
  - analyze
  - deploy

build-app:
  stage: build
  image: node:20-alpine
  script:
    - npm --version
    - npm ci
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    unprotect: false
    untracked: false
    when: on_success
    paths:
      - node_modules
      - .next/cache/
  artifacts:
    untracked: false
    when: on_success
    paths:
      - .next
      - build
    expire_in: 1 day

lint:
  stage: misc
  image: node:20-alpine
  needs:
    - job: build-app
  script:
    - npm ci
    - npm run lint

test:
  stage: misc
  image: node:20-alpine
  needs:
    - job: lint
  script:
    - npm ci
    - npm run test:ci

# FIXME: E2E testing would be modified later
# e2e-testing:
#   stage: misc
#   image: node:20-alpine
#   needs:
#     - job: test
#   parallel:
#     matrix:
#       - PROJECT: ["chromium"]
#         SHARD_INDEX: [1]
#         SHARD_TOTAL: 1
#   script:
#     - npm ci
#     - npx playwright install
#     - npx playwright test --workers 1 --project=$PROJECT --shard=$SHARD_INDEX/$SHARD_TOTAL
#   timeout: 20 hours 30 minutes
#   artifacts:
#     paths:
#       - ./playwright-report/
#       - ./Screenshot/
#     when: always
#     expire_in: 4 days

deploy-staging:
  stage: deploy
  image: node:20-alpine
  needs:
    - job: test
  script:
    - npm i
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN

deploy-prod:
  stage: deploy
  image: node:20-alpine
  only:
    - main
  needs:
    - job: test
  script:
    - npm i
    - npm install --global vercel
    - vercel pull --yes --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --token=$VERCEL_TOKEN
