import {Program} from "@/types/models/user.model.type";

const mockPrograms: Program[] = [
    {
        id: 1,
        uuid: "abc123",
        programName: "C# basic program",
        createdOn: "2024-02-20",
        createdBy: "admin",
        duration: "2 hours",
        status: "Active",
        createdDate: "2024-02-20",
    },
    {
        id: 2,
        uuid: "def456",
        programName: ".NET basic program",
        createdOn: "2024-02-21",
        createdBy: "admin",
        duration: "1 hour",
        status: "Inactive",
        createdDate: "2024-02-21",
    },
    {
        id: 3,
        uuid: "ghi789",
        programName: "DevOps Foundation",
        createdOn: "2024-02-22",
        createdBy: "admin",
        duration: "3 hours",
        status: "Draft",
        createdDate: "2024-02-22",
    },
    {
        id: 4,
        uuid: "jkl012",
        programName: "DevOps Foundation_2",
        createdOn: "2024-02-23",
        createdBy: "admin",
        duration: "4 hours",
        status: "Active",
        createdDate: "2024-02-23",
    },
    {
        id: 5,
        uuid: "mno345",
        programName: ".NET basic program_3",
        createdOn: "2024-02-24",
        createdBy: "admin",
        duration: "1.5 hours",
        status: "Inactive",
        createdDate: "2024-02-24",
    },
    {
        id: 6,
        uuid: "pqr678",
        programName: "IT Business Analyst Foundation_4",
        createdOn: "2024-02-25",
        createdBy: "admin",
        duration: "2.5 hours",
        status: "Draft",
        createdDate: "2024-02-25",
    },
    {
        id: 7,
        uuid: "stu901",
        programName: "Fullstack Java Web Developer_3",
        createdOn: "2024-02-26",
        createdBy: "admin",
        duration: "3 hours",
        status: "Active",
        createdDate: "2024-02-26",
    },
    {
        id: 8,
        uuid: "vwx234",
        programName: "Fullstack Java Web Developer_1",
        createdOn: "2024-02-27",
        createdBy: "admin",
        duration: "2 hours",
        status: "Inactive",
        createdDate: "2024-02-27",
    },
    {
        id: 9,
        uuid: "yza567",
        programName: ".NET basic program_2",
        createdOn: "2024-02-28",
        createdBy: "admin",
        duration: "4 hours",
        status: "Draft",
        createdDate: "2024-02-28",
    },
    {
        id: 10,
        uuid: "bcd890",
        programName: "Fullstack .NET Web Developer",
        createdOn: "2024-02-29",
        createdBy: "admin",
        duration: "3 hours",
        status: "Active",
        createdDate: "2024-02-29",
    },
];

export default mockPrograms;
