import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Sidebar from "./components/sidebar";
import { ReactNode } from "react";
import { NextAuthProvider } from "./components/auth/next-auth.provider";
import { Footer } from "./components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FAMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" data-theme="pastel">
      <body className={`${inter.className}`} data-theme="pastel">
        <ToastContainer autoClose={2000} />
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
